### ISSUE TITLE
yaml frontmatter loses syntax highlighting in mdx files

### ISSUE THREAD

**Issue by johnmathews** [preservim/vim-markdown#627]
Thanks for a great plugin.

I've noticed that in `.mdx` files yaml frontmatter doesnt have the same syntax highlighting applied as in `.md` files. 

The difference is like the below exmampes:

.md files
```yaml
---
title: >
  Photographer: Robert Doisneau
date: 2023-01-02 11:33:36
category: non-technical.snippet
tags: ['photography', 'photographer']
---

```

.mdx files
```text
---
title: >
  Photographer: Robert Doisneau
date: 2023-01-02 11:33:36
category: non-technical.snippet
tags: ['photography', 'photographer']
---
```
